### PR TITLE
F/project

### PR DESCRIPTION
**Pull request by eburgueno**
I cherry-picked Roy's fix and added mine on top. Thoughts?

### CODE REVIEW

**Comment by warrenson** [comment]
Looks good. Can we bring the tests @kiwiroy created as well? Testing is better than eyeballing...

**Comment by eburgueno** [comment]
> Can we bring the tests @kiwiroy created as well?

Absolutely. See #2

**Comment by kiwiroy** [comment]
LGTM. Maybe merge two first and rebase this one.

**Comment by eburgueno** [comment]
Should we bump the version as well? I can do a squash merge here

**Review by warrenson — APPROVED** [review]
Great. Yes, let's bump the version up a notch.

**Pull request merged**
